name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build-task-service:
    runs-on: ubuntu-latest
    name: Build and Test Task Service
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test Task Service with Gradle
        working-directory: task-service
        run: |
          ./gradlew clean build

  build-user-service:
    runs-on: ubuntu-latest
    name: Build and Test User Service
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test User Service with Gradle
        working-directory: user-service
        run: |
          ./gradlew clean build

  docker-task-service:
    needs: build-task-service
    runs-on: ubuntu-latest
    name: Build Docker Image for Task Service
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: task-service
        run: |
          docker build -t task-service-app -f Dockerfiles .
          docker images

  docker-user-service:
    needs: build-user-service
    runs-on: ubuntu-latest
    name: Build Docker Image for User Service
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: user-service
        run: |
          docker build -t user-service-app -f Dockerfiles .
          docker images